### PR TITLE
Updated transaction_detail_model.dart as changing to dynamic

### PR DESCRIPTION
**Pull request by muhd-ameen**
some of the variables return null in some scenarios, so changing them to dynamic will fix the null-returning issue

### CODE REVIEW

**Comment by GJJ2019** [comment]
Thanks for the PR but making it dynamic will be bad practice. I'll do some more research & update this model to work with nullable data

**Comment by muhd-ameen** [comment]
That makes sense, 👍 How about making the variable nullable?

**Comment by GJJ2019** [comment]
Yes we can make all nullable or optional one to nullable

**Comment by muhd-ameen** [comment]
> Yes we can make all nullable or optional one to nullable 

that's make sense

**Comment by GJJ2019** [comment]
fixed in v0.1.4

**Pull request closed without merging**
